# Logging Configuration
logging:
  version: 1
  formatters:
    report: 
      format: "Report Transformer - %(asctime)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: report
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console]  